<?php
function renewal_display_date(?string $value, bool $withTime = false): string {
    if (!$value) return 'Belum tersedia';
    $date = date_create_immutable($value);
    return $date ? $date->format($withTime ? 'd/m/Y, H:i' : 'd/m/Y') : $value;
}
function renewal_mail_label(?string $value): string {
    return ['sent'=>'Dihantar','sending'=>'Sedang dihantar','failed'=>'Gagal dihantar'][$value ?? ''] ?? 'Belum dihantar';
}
// Shared presentation for the two authenticated renewal pages.
function renewal_header(string $title, string $back): void { ?>
<!doctype html><html lang="ms"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo escape_html($title); ?> · MyRFID</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f7fb;font-family:system-ui,-apple-system,sans-serif;color:#17243a;line-height:1.5}header{background:#0b2239;color:#fff;padding:20px max(24px,calc((100vw - 1120px)/2));display:flex;align-items:center;justify-content:space-between;gap:20px}header a{color:#b8d9ff}main{max-width:1168px;margin:36px auto;padding:0 24px}h1{font-size:30px;margin:0 0 8px}h2{font-size:19px;margin:0 0 12px}p{margin:8px 0 18px}.muted{color:#64748b;font-size:13px}.card{background:#fff;border:1px solid #dde5ef;border-radius:14px;padding:24px;margin-bottom:20px;box-shadow:0 4px 15px #16243a05}.row{display:flex;flex-wrap:wrap;gap:12px;align-items:center}label{display:block;font-size:13px;font-weight:600}input,select,textarea{font:inherit;padding:10px;border:1px solid #cbd5e1;border-radius:7px;max-width:100%;background:#fff}input:not([type=checkbox]),textarea{width:100%}button,.button{font:inherit;display:inline-block;border:1px solid #cbd5e1;border-radius:8px;background:white;color:#1d3b61;padding:9px 14px;cursor:pointer;text-decoration:none;font-size:13px;font-weight:600}.primary{background:#246bfd;border-color:#246bfd;color:white}.danger{color:#a3293b}.badge{background:#edf3fc;padding:4px 9px;border-radius:6px;font-size:12px}.notice{padding:14px 18px;background:#e9f5ff;border:1px solid #cbdff5;border-radius:9px;margin-bottom:20px}.error{background:#fff0f1;color:#95263b}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.actions{padding-top:16px;margin-top:16px;border-top:1px solid #e6ebf3;display:flex;flex-wrap:wrap;gap:12px}.actions form{max-width:100%}.full{flex:1 1 100%}small{display:block;color:#64748b}details{margin-top:12px}summary{cursor:pointer;font-weight:600}a{color:#175bd5}.logout{border-color:#55718b;color:white;background:transparent}.no-margin{margin:0}button:disabled{opacity:.5;cursor:wait}@media(max-width:650px){main{padding:0 16px;margin:24px auto}.card{padding:18px}.grid{grid-template-columns:1fr}header{padding:16px}h1{font-size:25px}}

:root{--ink:#17263d;--muted:#6a7a90;--line:#e2e8f1;--blue:#246bfd}
body{background:#f5f7fb;color:var(--ink);font-size:14px;-webkit-font-smoothing:antialiased}
header{background:#fff;color:var(--ink);border-bottom:1px solid var(--line);padding:16px max(24px,calc((100vw - 1240px)/2));min-height:72px}header>strong{font-size:15px;letter-spacing:-.3px}header a{color:#53677e;font-size:13px;text-decoration:none}.logout{background:#fff;color:#41556d;border-color:var(--line)}
main{max-width:1288px;margin:36px auto;padding:0 24px}h1{font-size:29px;letter-spacing:-.8px;line-height:1.25;margin:0 0 10px}h2{font-size:16px;letter-spacing:-.3px;margin:0}.muted{color:var(--muted);line-height:1.6}main>p.muted{margin-bottom:28px;max-width:780px}.eyebrow{color:#246bfd;font-size:10px;font-weight:750;letter-spacing:1.4px;margin-bottom:9px;text-transform:uppercase}
.card{padding:24px;border-radius:12px;border-color:var(--line);box-shadow:0 3px 12px #15243c03;margin-bottom:18px}.row{gap:10px}button,.button{min-height:38px;display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:8px 13px;border-radius:7px;font-size:12px;line-height:1.4;transition:background .15s,border-color .15s}button:hover,.button:hover{background:#f2f6fc;border-color:#b6c8e0}.primary:hover{background:#1758df;border-color:#1758df}button:focus-visible,a:focus-visible,summary:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid #8bb6ff;outline-offset:3px}
select,input:not([type=checkbox]),textarea{min-height:42px;border-color:#d7e0ec;border-radius:7px;font-size:13px;padding:10px 12px;color:var(--ink)}select{width:100%}label{color:#52677e;font-size:12px;margin-bottom:5px}input[type=checkbox]{accent-color:var(--blue);vertical-align:middle;margin-right:8px}.create-panel{display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,1fr);gap:32px;align-items:center;border-left:3px solid var(--blue)}.create-panel p{margin:8px 0 0;max-width:460px}.create-controls{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:end}.create-controls label{margin:0}.create-controls button{height:42px}.toolbar{display:flex;justify-content:space-between;align-items:center;gap:20px;margin:30px 0 14px}.toolbar h2{font-size:17px}.filter-form{display:flex;align-items:center;gap:8px;max-width:420px}.filter-form select{min-height:38px;padding:8px 10px;max-width:280px}.count{display:inline-flex;padding:3px 8px;border:1px solid var(--line);border-radius:5px;margin-left:8px;font-size:11px;color:var(--muted);font-weight:500;vertical-align:middle}
.renewal-record{padding:0;overflow:hidden}.record-head{padding:21px 24px;display:flex;justify-content:space-between;gap:20px;align-items:flex-start;border-bottom:1px solid var(--line)}.record-head h2{font-size:17px;margin:0 0 4px;text-transform:none;overflow-wrap:anywhere}.record-head small{font-size:12px}.record-body{padding:22px 24px}.record-reference{font-size:11px;color:var(--muted);font-family:ui-monospace,SFMono-Regular,monospace;overflow-wrap:anywhere}.record-summary{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:18px}.record-summary h2{font-size:13px;font-weight:600}.badge{display:inline-flex;align-items:center;gap:6px;white-space:nowrap;padding:5px 10px;border-radius:6px;font-size:11px;font-weight:650;background:#edf3fc;color:#4c6485}.badge:before{content:'';width:6px;height:6px;border-radius:50%;background:currentColor}.badge-paid{color:#08724f;background:#eaf8f1}.badge-pending{color:#946019;background:#fff6e5}.badge-submitted{color:#2358bc;background:#edf3ff}.badge-cancelled{color:#718093;background:#eef1f5}
.grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.grid>div{padding:0 20px;border-left:1px solid var(--line)}.grid>div:first-child{padding-left:0;border-left:0}.grid small{font-size:11px;margin-bottom:5px}.grid strong{font-size:16px;letter-spacing:-.3px}.renewal-success{display:flex;align-items:center;gap:9px;margin:18px 0 0;background:#f0faf5;border:1px solid #d7eee2;border-radius:7px;padding:11px 14px;color:#257052;font-size:12px}.document-links{margin-top:18px;gap:8px}.document-links .button{background:#f8fafc;border-color:#e0e7f0;color:#435c7a}.record-bottom{background:#fbfcfe;border-top:1px solid var(--line);padding:14px 24px}.record-bottom .actions{margin:0;padding:0;border:0}.mail-details{margin:0 0 14px}.mail-details summary{font-size:12px;font-weight:500;color:#667991}.mail-details p{margin:12px 0 0;font-size:12px;line-height:1.9}.actions details{margin:4px 0 0;width:100%;border:1px solid var(--line);background:white;border-radius:8px;padding:12px 14px}.actions summary{font-size:12px;line-height:1.6}.actions details[open]>summary{margin-bottom:14px}.actions details p{font-size:12px}.actions form>button{margin-top:8px}.actions>form>button{margin-top:0}.notice{font-size:13px;line-height:1.65}.pagination{justify-content:space-between;margin-top:24px;color:var(--muted);font-size:12px}.empty-state{text-align:center;padding:48px 24px;color:var(--muted)}.empty-state strong{display:block;font-size:16px;color:var(--ink);margin-bottom:8px}
@media(max-width:850px){.create-panel{grid-template-columns:1fr;gap:18px}.toolbar{align-items:flex-start;flex-direction:column;gap:12px}.filter-form{width:100%;max-width:none}.filter-form select{flex:1;max-width:none}.record-head,.record-body,.record-bottom{padding-left:20px;padding-right:20px}}
@media(max-width:560px){main{padding:0 16px;margin:25px auto}header{padding:14px 16px}header>strong{font-size:13px}header .row{gap:10px}.card{padding:18px}.renewal-record{padding:0}.create-controls{grid-template-columns:1fr}.create-controls button{width:100%}.grid{grid-template-columns:1fr;gap:15px}.grid>div{border-left:0;padding:0;display:flex;align-items:center;justify-content:space-between;gap:12px}.grid strong{font-size:14px}.grid small{margin:0}.record-head{flex-direction:column;gap:12px}.record-summary{align-items:flex-start}.record-reference{font-size:10px}.document-links{align-items:stretch}.document-links .button{flex:1}h1{font-size:25px}.renewal-success{align-items:flex-start;flex-wrap:wrap}}
</style></head><body><header><strong>MyRFID · Pembaharuan</strong><div class="row"><a href="<?php echo escape_html($back); ?>">Kembali</a><form method="post" action="logout.php" class="no-margin"><input type="hidden" name="csrf_token" value="<?php echo escape_html(csrf_token()); ?>"><button class="logout">Log keluar</button></form></div></header><main><div class="eyebrow">Pengurusan langganan</div><h1><?php echo escape_html($title); ?></h1>
<?php }
function renewal_footer(): void { ?>
</main><script>document.querySelectorAll('form[data-confirm]').forEach(function(f){f.addEventListener('submit',function(e){if(!confirm(f.dataset.confirm)){e.preventDefault();return;}var b=f.querySelector('button[type=submit]');if(b)b.disabled=true;});});</script></body></html>
<?php }
function renewal_hidden(int $id,string $action): void { ?>
<input type="hidden" name="csrf_token" value="<?php echo escape_html(csrf_token()); ?>"><input type="hidden" name="id" value="<?php echo $id; ?>"><input type="hidden" name="action" value="<?php echo escape_html($action); ?>">
<?php }
function renewal_summary(array $r): void { ?>
<div class="record-summary"><span class="record-reference"><?php echo escape_html($r['reference']); ?></span><span class="badge badge-<?php echo escape_html(in_array($r['status'],['paid','pending','submitted','cancelled'],true)?$r['status']:'pending'); ?>"><?php echo escape_html(renewal_status($r['status'])); ?></span></div>
<div class="grid"><div><small>Pelan / tempoh</small><strong><?php echo escape_html($r['plan_name']); ?> · 12 bulan</strong></div><div><small>Jumlah pembaharuan</small><strong>RM <?php echo number_format((float)$r['amount'],2); ?></strong></div><div><small>Sebut harga sah sehingga</small><strong><?php echo escape_html(renewal_display_date($r['valid_until'])); ?></strong><?php if($r['valid_until']<date('Y-m-d') && !in_array($r['status'],['paid','cancelled'],true)): ?><small class="danger">Tamat tempoh</small><?php endif; ?></div></div>
<?php if($r['new_expiry']): ?><div class="renewal-success"><span aria-hidden="true">✓</span> Pembaharuan disahkan · Langganan sehingga <strong><?php echo escape_html(renewal_display_date($r['new_expiry'])); ?></strong></div><?php endif; ?>
<div class="row document-links"><a class="button" href="renewal_download.php?id=<?php echo (int)$r['id']; ?>">↓ Sebut harga PDF</a><?php if($r['receipt_path']): ?><a class="button" href="renewal_download.php?id=<?php echo (int)$r['id']; ?>&amp;type=receipt">↓ Resit bayaran</a><?php endif; ?></div>
<?php }